const routes = {
    home: '/',
    iphone: '/iphone',
    iphone14series: '/iphone14series',
    iphone13series: '/iphone13series',
    iphone12series: '/iphone12series',
    iphone11series: '/iphone11series',
    iphoneSE: '/iphoneSE',
    ipad: '/ipad',
    ipadprom1: '/ipad_pro_m1',
    ipadprom2: '/ipad_pro_m2',
    ipadair: '/ipad_air',
    ipad9: 'ipad_9',
    ipad10: 'ipad_10',
    ipadmini: 'ipad_mini',
    mac: '/mac',
    macbookpro: '/macbook_pro',
    macbookair: '/macbook_air',
    imac: '/imac',
    macmini: '/mac_mini',
    macpro: '/mac_pro',
    macstudio: '/mac_studio',
    watch: '/watch',
    applewatchultra: '/apple_watch_ultra',
    applewatchseries8: '/apple_watch_series_8',
    applewatchseries7: '/apple_watch_series_7',
    applewatchseries6: '/apple_watch_series_6',
    applewatchse: '/apple_watch_se',
    applewatchseries3: '/apple_watch_series_3',
    soundpage: '/soundpage',
    servicepage: '/servicepage',
    accessorypage: '/accessorypage',
    productitem: '/:namePath/:category',
};

export default routes;
